name: aichat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.17.0
  google_sign_in: 5.3.1
  cloud_firestore: 3.1.15
  firebase_storage: 10.2.16
  lottie: 1.3.0
  introduction_screen: 3.0.2
  avatar_glow: 2.0.2
  emoji_picker_flutter: 1.1.2
  get_storage: 2.0.3
  intl: 0.17.0
  image_picker: 0.8.5+3
  firebase_auth: 3.3.18
  flutter_svg: 1.0.3
  image_cropper: 2.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
    - assets/svg/

  fonts: 
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
          
  uses-material-design: true

