// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNA7yEk2jvHFHf7RITszuSN6sMH16f-mw',
    appId: '1:90569147103:web:b453303f2775369b619f6a',
    messagingSenderId: '90569147103',
    projectId: 'aichatv2-47acd',
    authDomain: 'aichatv2-47acd.firebaseapp.com',
    storageBucket: 'aichatv2-47acd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5HjbKQy_FJp8TkLqxp_OmKIbuSOlF1iQ',
    appId: '1:90569147103:android:dcadc2cbbf9353b0619f6a',
    messagingSenderId: '90569147103',
    projectId: 'aichatv2-47acd',
    storageBucket: 'aichatv2-47acd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcSUK9UKmoB1dn4wmAcFeIbWrJkfThkiY',
    appId: '1:90569147103:ios:ed1060f7ceb47666619f6a',
    messagingSenderId: '90569147103',
    projectId: 'aichatv2-47acd',
    storageBucket: 'aichatv2-47acd.appspot.com',
    androidClientId: '90569147103-dppme22jmj8pce13irvr2m5leij6uudp.apps.googleusercontent.com',
    iosClientId: '90569147103-39facun5ig6fqqvhunn15q8sjq4b7h72.apps.googleusercontent.com',
    iosBundleId: 'com.ihsan.amel.aichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcSUK9UKmoB1dn4wmAcFeIbWrJkfThkiY',
    appId: '1:90569147103:ios:ed1060f7ceb47666619f6a',
    messagingSenderId: '90569147103',
    projectId: 'aichatv2-47acd',
    storageBucket: 'aichatv2-47acd.appspot.com',
    androidClientId: '90569147103-dppme22jmj8pce13irvr2m5leij6uudp.apps.googleusercontent.com',
    iosClientId: '90569147103-39facun5ig6fqqvhunn15q8sjq4b7h72.apps.googleusercontent.com',
    iosBundleId: 'com.ihsan.amel.aichat',
  );
}
